#!/bin/bash
dirin=/work/ka1081/DYAMOND/IFS-4km/

for d in 11; do
 #cdo --eccodes select,name=clwc ${dirin}mars_out_ml_moist.240 test.grb
 #cdo -f nc -setgridtype,regular test.grb test.nc
 #cdo -P 16 -f nc -O -fldmean -sellonlatbox,-50,-30,0,20 test.nc IFS_qc_dc_mean_20160811_00.nc
 cdo --eccodes select,name=geopotential ${dirin}mars_out_sfc_ps_orog_gg.240 test.grb
 cdo -f nc -setgridtype,regular test.grb test.nc
 cdo -P 16 -f nc -O -fldmean -sellonlatbox,-50,-51,0,1 test.nc IFS_h_dc_mean_20160811_00.nc
done

