#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
description     namelist of model variables
author			Christoph Heim
date created    09.09.2019
date changed    11.06.2022
usage           use in another script
"""
###############################################################################
import os, copy
from package.constants import CON_LH_EVAP,CON_LH_SUBL,CON_CP_AIR
###############################################################################

# zonal
dimx = 'x'
# meridional
dimy = 'y'
# vertical
dimz = 'z'
# time
dimt = 't'
# hour
dimh = 'h'
# month
dimm = 'm'
# year
dimY = 'Y'



nlv = {

###############################################################################
## COORDINATE VARIABLES
'COORD_ALT' :{
    'lo_name'   :'height',
    'label'     :'z',
    'units'      :'$m$',
    'dims'      :[dimz],
    'plt_fact'  :1E-3,
    'plt_units' :'$km$',
},
'COORD_RELALT' :{
    'lo_name'   :'height relative to inversion height',
    'label'     :'z/z$_{i}$',
    'units'      :'',
    'dims'      :[dimz],
},
'COORD_LON' :{
    'lo_name'   :'longitude',
    'label'     :'longitude',
    #'units'      :'$°$ East',
    'units'      :'',
    'dims'      :[dimx],
},
'COORD_LAT' :{
    'lo_name'   :'latitude',
    'label'     :'latitude',
    #'units'      :'$°$ East',
    'units'      :'',
    'dims'      :[dimy],
},
'COORD_DATETIME' :{
    'lo_name'   :'date and time',
    'label'     :'date',
    'units'      :'',
    'dims'      :[dimt],
},
'COORD_HOUR' :{
    'lo_name'   :'day time',
    'label'     :'time',
    'units'      :'UTC',
    'dims'      :[dimh],
},
'COORD_MONTH' :{
    'lo_name'   :'month',
    'label'     :'month',
    'units'      :'',
    'dims'      :[dimm],
},
'COORD_YEAR' :{
    'lo_name'   :'year',
    'label'     :'year',
    'units'      :'',
    'dims'      :[dimY],
},

###############################################################################
## NORMAL VARIABLES
'HSURF' :{
    'lo_name'   :'surface elevation',
    'label'     :'elevation',
    'units'      :'$m$',
    'dims'      :[dimx,dimy],
},
'WSOIL' :{
    'lo_name'   :'soil water column depth',
    'label'     :'soil water',
    'units'      :'$m$',
    'dims'      :[dimt,dimx,dimy,dimz],
},
'TSOIL' :{
    'lo_name'   :'soil layer temperature',
    'label'     :'soil temperature',
    'units'      :'$K$',
    'dims'      :[dimt,dimx,dimy,dimz],
},


'U' :{
    'lo_name'   :'zonal wind speed',
    'label'     :'u-wind',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'UI' :{
    'lo_name'   :'x wind at inversion',
    'label'     :'zonal wind speed',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'V' :{
    'lo_name'   :'meridional wind speed',
    'label'     :'v-wind',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'VI' :{
    'lo_name'   :'y wind at inversion',
    'label'     :'meridional wind speed',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'UV' :{
    'lo_name'   :'horizontal wind speed',
    'label'     :'wind speed',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'UVDIV' :{
    'lo_name'   :'divergence of the horizontal wind',
    'label'     :r"$\nabla _{h} (v_{h})$",
    'units'      :'$s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'UVFLXDIV' :{
    'lo_name'   :'divergence of the horizontal mass flux',
    'label'     :r"$\nabla _{h} (v_{h} \rho)$",
    'units'      :'$kg$ $m^{-3}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'UVFLXDIVNORMI' :{
    'lo_name'   :'divergence of the horizontal mass flux',
    'label'     :r"$\nabla _{h} (v_{h} \rho)$",
    'units'      :'$kg$ $m^{-3}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'W' :{
    'lo_name'   :'vertical wind speed',
    #'label'     :'w-wind',
    'label'     :'W',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :-0.1*3600*24,
    'plt_units' :'$hPa$ $d^{-1}$',
},
#'WP' :{
#    'lo_name'   :'vertical wind speed in pressure',
#    'label'     :'vertical wind',
#    'units'     :'$Pa$ $s^{-1}$',
#    'dims'      :[dimx,dimy,dimz,dimt],
#},
'WI' :{
    'lo_name'   :'vertical wind speed at inversion',
    'label'     :'vertical wind',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'WTURB' :{
    'lo_name'   :'turbulent vertical velocity',
    'label'     :r"$\sigma_{w}$",
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'WTURBNORMI' :{
    'lo_name'   :'turbulent vertical velocity',
    'label'     :r"$\sigma_{w}$",
    'units'      :'$m$ $s^{-1}$',
    #'units'      :'$s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'WTURBNORMISCI' :{
    'lo_name'   :'turbulent vertical velocity',
    'label'     :r"$\sigma_{w}/z_{i}$",
    'units'     :'$s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    #'plt_fact'  :3600,
    #'plt_units' :'$h^{-1}$',
},
'UFLX' :{
    'lo_name'   :'zonal mass flux',
    'label'     :r'$\rho$u',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'VFLX' :{
    'lo_name'   :'meridional mass flux',
    'label'     :r'$\rho$v',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'WFLX' :{
    'lo_name'   :'vertical mass flux',
    'label'     :r'$\rho$w',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'CLDWFLXLCL' :{
    'lo_name'   :'in-cloud vertical mass flux at LCL',
    'label'     :'cumulus mass flux',
    'units'     :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'CLDWFLXLOWCLDBASE' :{
    'lo_name'   :'in-cloud vertical mass flux at low-cloud base',
    'label'     :'cumulus mass flux',
    'units'     :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'CSWFLXLOWCLDBASE' :{
    'lo_name'   :'clear-sky vertical mass flux at low-cloud base',
    'label'     :'clear-sky mass flux',
    'units'     :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'WFLXI' :{
    'lo_name'   :'vertical mass flux into the MBL',
    'label'     :'$F^{z}_{MBL}$',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'ENTR' :{
    'lo_name'   :'entrainment velocity',
    #'label'     :'entrainment',
    'label'     :'E',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :-0.1*3600*24,
    #'plt_units' :'$hPa$ $d^{-1}$',
},
'ENTRH' :{
    'lo_name'   :'entrainment velocity diagnosed horizontally',
    'label'     :'E$_h$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :-0.1*3600*24,
    #'plt_units' :'$hPa$ $d^{-1}$',
},
'ENTRV' :{
    'lo_name'   :'entrainment velocity diagnosed vertically',
    'label'     :'E$_v$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :-0.1*3600*24,
    #'plt_units' :'$hPa$ $d^{-1}$',
},
'ENTRSCL' :{
    'lo_name'   :'entrainment velocity',
    #'label'     :'entrainment',
    'label'     :'E$^{SCL}$',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :-0.1*3600*24,
    #'plt_units' :'$hPa$ $d^{-1}$',
},
'ENTRHSCL' :{
    'lo_name'   :'entrainment velocity diagnosed horizontally',
    'label'     :'E$^{SCL}$$_h$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :-0.1*3600*24,
    'plt_units' :'$hPa$ $d^{-1}$',
    #'plt_fact'  :-0.1*3600*24,
    #'plt_units' :'$hPa$ $d^{-1}$',
},
'ENTRVSCL' :{
    'lo_name'   :'entrainment velocity diagnosed vertically',
    'label'     :'E$^{SCL}$$_v$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :-0.1*3600*24,
    #'plt_units' :'$hPa$ $d^{-1}$',
},
'AW' :{
    'lo_name'   :'velocity of vertical circulations',
    'label'     :'|w|',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'AWD' :{
    'lo_name'   :'downward velocity of vertical circulations',
    'label'     :'w up',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'AWU' :{
    'lo_name'   :'upward velocity of vertical circulations',
    'label'     :'w down',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'KEW' :{
    'lo_name'   :'grid-scale vertical kinetic energy',
    'label'     :'grid-scale vertical kinetic energy',
    'units'      :'$J$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'T' :{
    'lo_name'   :'temperature',
    'label'     :'T',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'TV' :{
    'lo_name'   :'virtual temperature',
    'label'     :'virtual temperature',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'TDEW' :{
    'lo_name'   :'dew point temperature',
    'label'     :'T$_d$',
    'units'      :'$°C$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'POTT' :{
    'lo_name'   :'potential temperature',
    #'label'     :'potential temperature',
    'label'     :r"$\theta$",
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'POTTV' :{
    'lo_name'   :'virtual potential temperature',
    'label'     :r'$\theta_v$',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'EQPOTT' :{
    'lo_name'   :'equivalent potential temperature',
    'label'     :'$\theta _{e}$',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'POTTMBLI' :{
    'lo_name'   :'mean potential temperature in MBL',
    'label'     :r"$\theta |_{MBL}$",
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimt],
},
#'LAPSE' :{
#    'lo_name'   :'environmental lapse rate',
#    'label'     :'$\Tau$',
#    'units'      :'$K$ $m^{-1}$',
#    'dims'      :[dimx,dimy,dimz,dimt],
#    'plt_fact'  :1000,
#    'units'      :'$K$ $km^{-1}$',
#},
'BVF' :{
    'lo_name'   :'Brunt-Väisälä frequency',
    'label'     :'$N^2$',
    'units'      :'$s^{-2}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    #'plt_fact'  :3600,
    #'plt_units' :'$min^{-2}$',
},
'BVFNORMI' :{
    'lo_name'   :'Brunt-Väisälä frequency',
    'label'     :'$N^2$',
    'units'      :'$s^{-2}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    #'plt_fact'  :3600,
    #'plt_units' :'$min^{-2}$',
},
'P' :{
    'lo_name'   :'pressure',
    'label'     :'pressure',
    'units'      :'$Pa$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'PPERT' :{
    'lo_name'   :'pressure perturbation',
    'label'     :'pressure pert.',
    'units'      :'$Pa$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'ALT' :{
    'lo_name'   :'altitude',
    'label'     :'altitude',
    'units'      :'$m$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'RHO' :{
    'lo_name'   :'density',
    'label'     :'density',
    'units'      :'$kg$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'RHOI' :{
    'lo_name'   :'density at inversion',
    'label'     :'density',
    'units'      :'$kg$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimt],
},
'BUOYIFLX' :{
    'lo_name'   :'buoyancy flux',
    'label'     :'buoyancy flux',
    'units'      :'$m^2$ $s^{-3}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'UPDBUOYI' :{
    'lo_name'   :'updraft buoyancy',
    'label'     :'updraft buoyancy',
    'units'      :'$m$ $s^{-2}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'QV' :{
    'lo_name'   :'specific water vapor content',
    'label'     :'$q_v$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'AQV' :{
    'lo_name'   :'absolute water vapor content',
    'label'     :'$c_v$',
    'units'      :'$kg$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    #'plt_fact'  :1000,
    #'plt_units' :'$g$ $m^{-3}$',
},
'QVDIV' :{
    'lo_name'   :'divergence of specific water vapor content',
    'label'     :r"$v\nabla q_{v}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIVTURB' :{
    'lo_name'   :'flux divergence of specific water vapor content',
    'label'     :r"$\overline{v'\nabla q_{v}'}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIVMEAN' :{
    'lo_name'   :'mean flow divergence of specific water vapor content',
    'label'     :r"$\overline{v}$ $\nabla \overline{q_{v}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV' :{
    'lo_name'   :'horizontal divergence of specific water vapor content',
    'label'     :r"$v_{h}\nabla _{h} q_{v}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIVMEAN' :{
    'lo_name'   :'horizontal mean flow divergence of specific water vapor content',
    'label'     :r"$\overline{v_{h}}$ $\nabla _{h} \overline{q_{v}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIVTURB' :{
    'lo_name'   :'horiz. flux divergence of specific water vapor content',
    'label'     :r"$\overline{v_{h}'\nabla _{h} q_{v}'}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVXDIV' :{
    'lo_name'   :'longitudinal divergence of specific water vapor content',
    'label'     :r"$u\frac{\partial q_{v}}{\partial lon}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVYDIV' :{
    'lo_name'   :'latitudinal divergence of specific water vapor content',
    'label'     :r"$v\frac{\partial q_{v}}{\partial lat}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV' :{
    'lo_name'   :'vertical divergence of specific water vapor content',
    'label'     :r"$w\frac{\partial q_{v}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIVMEAN' :{
    'lo_name'   :'vertical mean flow divergence of specific water vapor content',
    'label'     :r"$\overline{w}$ $\frac{\partial \overline{q_{v}}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIVTURB' :{
    'lo_name'   :'vert. flux divergence of specific water vapor content',
    'label'     :r"$\overline{w'\frac{\partial q_{v}'}{\partial z}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVUVDIVTURB' :{
    'lo_name'   :'vert. upward flux divergence of specific water vapor content',
    'label'     :r"$\overline{w_{+}'\frac{\partial q_{v}'}{\partial z}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDVDIVTURB' :{
    'lo_name'   :'vert. downward flux divergence of specific water vapor content',
    'label'     :r"$\overline{w_{-}'\frac{\partial q_{v}'}{\partial z}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIV2' :{
    'lo_name'   :'divergence of specific water vapor content',
    'label'     :r"$q_v\nabla v$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIV2TURB' :{
    'lo_name'   :'flux divergence of specific water vapor content',
    'label'     :r"$\overline{q_{v}'\nabla v'}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIV2MEAN' :{
    'lo_name'   :'mean flow divergence of specific water vapor content',
    'label'     :r"$\overline{q_{v}}$ $\nabla \overline{v}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV2' :{
    'lo_name'   :'horizontal divergence of specific water vapor content',
    'label'     :r"$q_{v}\nabla _{h} v_{h}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV2MEAN' :{
    'lo_name'   :'horizontal mean flow divergence of specific water vapor content',
    'label'     :r"$\overline{q_{v}}$ $\nabla _{h} \overline{v_{h}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV2TURB' :{
    'lo_name'   :'horiz. flux divergence of specific water vapor content',
    'label'     :r"$q_{v}'\nabla _{h} \overline{v_{h}'}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV2' :{
    'lo_name'   :'vertical divergence of specific water vapor content',
    'label'     :r"$q_{v}\frac{\partial w}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV2MEAN' :{
    'lo_name'   :'vertical mean flow divergence of specific water vapor content',
    'label'     :r"$\overline{q_{v}}$ $\frac{\partial \overline{w}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV2TURB' :{
    'lo_name'   :'vert. flux divergence of specific water vapor content',
    'label'     :r"$\overline{q_{v}'\frac{\partial w'}{\partial z}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIV3' :{
    'lo_name'   :'divergence of specific water vapor content',
    'label'     :r"$\nabla (vq_v)$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIV3TURB' :{
    'lo_name'   :'flux divergence of specific water vapor content',
    'label'     :r"$\nabla \overline{(v'q_{v}')}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVDIV3MEAN' :{
    'lo_name'   :'mean flow divergence of specific water vapor content',
    'label'     :r"$\nabla \overline{(vq_{v})}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV3' :{
    'lo_name'   :'horizontal divergence of specific water vapor content',
    'label'     :r"$\nabla _{h} (v_{h}q_{v})$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV3MEAN' :{
    'lo_name'   :'horizontal mean flow divergence of specific water vapor content',
    'label'     :r"$\nabla _{h} \overline{(v_{h} q_{v})}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVHDIV3TURB' :{
    'lo_name'   :'horiz. flux divergence of specific water vapor content',
    'label'     :r"$\nabla _{h} \overline{(v_{h}' q_{v}')}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV3' :{
    'lo_name'   :'vertical divergence of specific water vapor content',
    'label'     :r"$\frac{\partial (wq_{v})}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV3MEAN' :{
    'lo_name'   :'vertical mean flow divergence of specific water vapor content',
    'label'     :r"$\frac{\partial \overline{wq_{v}}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QVVDIV3TURB' :{
    'lo_name'   :'vert. flux divergence of specific water vapor content',
    'label'     :r"$\overline{\frac{\partial w'q_{v}'}{\partial z}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},

'QVVFLX' :{
    'lo_name'   :'meridional moisture flux',
    'label'     :'qv flux',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'QVWFLX' :{
    'lo_name'   :'vertical moisture flux',
    'label'     :'qv flux',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000*24*3600/1000, # mm/m s/h, h/d density water
    'plt_units' :'$mm$ $d^{-1}$',
},
'QVWFLXINV' :{
    'lo_name'   :'vertical moisture flux at inversion',
    'label'     :'qv flux',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1000*24*3600/1000, # mm/m s/h, h/d density water
    'plt_units' :'$mm$ $d^{-1}$',
},


'AQVHDIV3' :{
    'lo_name'   :'horizontal divergence of absolute water vapor content',
    'label'     :r"$\nabla _{h} (v_{h}q_{v})$",
    'units'     :'$kg$ $m^{-3}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'WVPHCONV' :{
    'lo_name'   :'horizontal convergence of column water vapor',
    'label'     :r"$\int_z\nabla _{h} (v_{h}q_{v}\rho)$",
    'units'     :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3*24*3600/1E3, # mm/m, h/d, s/h, water density
    'plt_units' :'$mm$ $d^{-1}$',
},
'AQIHDIV3' :{
    'lo_name'   :'horizontal divergence of absolute cloud ice content',
    'label'     :r"$\nabla _{h} (v_{h}q_{i})$",
    'units'     :'$kg$ $m^{-3}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'IWPHCONV' :{
    'lo_name'   :'horizontal convergence of column ice water',
    'label'     :r"$\int_z\nabla _{h} (v_{h}q_{i}\rho)$",
    'units'     :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3*24*3600/1E3, # mm/m, h/d, s/h, water density
    'plt_units' :'$mm$ $d^{-1}$',
},


'QC' :{
    'lo_name'   :'specific cloud water content',
    'label'     :'$q_c$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'CLDQX' :{
    'lo_name'   :'specific cloud liquid and ice water content',
    'label'     :'$q_c,i$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'QCDIV' :{
    'lo_name'   :'divergence of specific cloud liquid water content',
    'label'     :r"$v\nabla q_{c}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCDIVTURB' :{
    'lo_name'   :'flux divergence of cloud liquid water content',
    'label'     :r"$\overline{v'\nabla q_{c}'}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCDIVMEAN' :{
    'lo_name'   :'mean flow divergence of cloud liquid water content',
    'label'     :r"$\overline{v}$ $\nabla \overline{q_{c}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCHDIV' :{
    'lo_name'   :'horizontal divergence of specific cloud liquid water content',
    'label'     :r"$v_{h}\nabla _{h} q_{c}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCHDIVMEAN' :{
    'lo_name'   :'horizontal mean flow divergence of cloud liquid water content',
    'label'     :r"$\overline{v_{h}}$ $\nabla _{h} \overline{q_{c}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCHDIVTURB' :{
    'lo_name'   :'horiz. flux divergence of cloud liquid water content',
    'label'     :r"$\overline{v_{h}'\nabla _{h} q_{c}'}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCVDIV' :{
    'lo_name'   :'vertical divergence of specific cloud liquid water content',
    'label'     :r"$w\frac{\partial q_{c}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCVDIVMEAN' :{
    'lo_name'   :'vertical mean flow divergence of cloud liquid water content',
    'label'     :r"$\overline{w}$ $\frac{\partial \overline{q_{c}}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'QCVDIVTURB' :{
    'lo_name'   :'vert. flux divergence of cloud liquid water content',
    'label'     :r"$\overline{w'\frac{\partial q_{c}'}{\partial z}}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},


'QI' :{
    'lo_name'   :'specific cloud ice content',
    'label'     :'$q_i$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'QIDIV3' :{
    'lo_name'   :'divergence of specific cloud ice content',
    'label'     :r"$\nabla vq_{i}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*CON_LH_SUBL/CON_CP_AIR,
    'plt_units' :'$K$ $h^{-1}$',
},
'QIHDIV3' :{
    'lo_name'   :'horizontal divergence of specific cloud ice content',
    'label'     :r"$\nabla _{h} v_{h}q_{i}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*CON_LH_SUBL/CON_CP_AIR,
    'plt_units' :'$K$ $h^{-1}$',
},
'QIVDIV3' :{
    'lo_name'   :'vertical divergence of specific cloud ice content',
    'label'     :r"$\frac{\partial wq_{i}}{\partial z}$",
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*CON_LH_SUBL/CON_CP_AIR,
    'plt_units' :'$K$ $h^{-1}$',
},
'AQI' :{
    'lo_name'   :'absolute cloud ice content',
    'label'     :'$c_i$',
    'units'      :'$kg$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'QR' :{
    'lo_name'   :'specific rain content',
    'label'     :'$q_r$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'QG' :{
    'lo_name'   :'specific graupel content',
    'label'     :'$q_g$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'QS' :{
    'lo_name'   :'specific snow content',
    'label'     :'$q_s$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'DIABH' :{
    'lo_name'   :'diabatic heating',
    'label'     :'diabatic heating',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600,
    'plt_units' :'$K$ $h^{-1}$',
},
'DIABHNORMI' :{
    'lo_name'   :'diabatic heating',
    'label'     :'diabatic heating',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600,
    'plt_units' :'$K$ $h^{-1}$',
},
'LATH' :{
    'lo_name'   :'latent heating tendency',
    #'label'     :'latent heating',
    'label'     :r"$v\nabla \theta$ - $v\nabla \theta _e$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600,
    'plt_units' :'$K$ $h^{-1}$',
},
'DIABM' :{
    'lo_name'   :'diabatic moistening',
    'label'     :'diabatic moistening',
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'DIABMNORMI' :{
    'lo_name'   :'diabatic moistening',
    'label'     :'diabatic moistening',
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'UNORMI' :{
    'lo_name'   :'x wind',
    'label'     :'zonal wind speed',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'VNORMI' :{
    'lo_name'   :'y wind',
    'label'     :'meridional wind speed',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'UVNORMI' :{
    'lo_name'   :'horizontal wind speed',
    'label'     :'horizontal wind',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'PNORMI' :{
    'lo_name'   :'pressure',
    'label'     :'pressure',
    'units'     :'$Pa$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'POTTDIV' :{
    'lo_name'   :'divergence of potential temperature',
    'label'     :r"$v\nabla \theta$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTDIVMEAN' :{
    'lo_name'   :'mean flow divergence of potential temperature',
    'label'     :r"$\overline{v}$ $\nabla \overline{\theta}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTDIVTURB' :{
    'lo_name'   :'flux divergence of potential temperature',
    'label'     :r"$\overline{v'\nabla \theta'}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},

'POTTHDIV' :{
    'lo_name'   :'horizontal divergence of potential temperature',
    'label'     :r"$v_{h}\nabla _{h} \theta$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTHDIVMEAN' :{
    'lo_name'   :'horizontal mean flow divergence of potential temperature',
    'label'     :r"$\overline{v_{h}}$ $\nabla _{h} \overline{\theta}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTHDIVTURB' :{
    'lo_name'   :'horiz. flux divergence of potential temperature',
    'label'     :r"$\overline{v_{h}'\nabla _{h} \theta'}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTXDIV' :{
    'lo_name'   :'longitudinal divergence of potential temperature',
    'label'     :r"$u\frac{\partial \theta}{\partial lon}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTYDIV' :{
    'lo_name'   :'latitudinal divergence of potential temperature',
    'label'     :r"$v\frac{\partial \theta}{\partial lat}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},


'POTTVDIV' :{
    'lo_name'   :'vertical divergence of potential temperature',
    'label'     :r"$w\frac{\partial \theta}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVDIVMEAN' :{
    'lo_name'   :'vertical mean flow divergence of potential temperature',
    'label'     :r"$\overline{w}$ $\frac{\partial \overline{\theta}}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVDIVTURB' :{
    'lo_name'   :'vert. flux divergence of potential temperature',
    'label'     :r"$\overline{w'\frac{\partial \theta'}{\partial z}}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},

'POTTDIV2' :{
    'lo_name'   :'divergence of potential temperature',
    'label'     :r"$\theta \nabla v$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTHDIV2' :{
    'lo_name'   :'horizontal divergence of potential temperature',
    'label'     :r"$\theta \nabla _{h} v_{h}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVDIV2' :{
    'lo_name'   :'vertical divergence of potential temperature',
    'label'     :r"$\theta \frac{\partial w}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},

'POTTDIV3' :{
    'lo_name'   :'divergence of potential temperature',
    'label'     :r"$\nabla (v\theta)$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTHDIV3' :{
    'lo_name'   :'horizontal divergence of potential temperature',
    'label'     :r"$\nabla _{h} (v_{h}\theta)$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVDIV3' :{
    'lo_name'   :'vertical divergence of potential temperature',
    'label'     :r"$\frac{\partial (w\theta)}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},


'POTTDIV4' :{
    'lo_name'   :'divergence of potential temperature',
    'label'     :r"$\nabla (v \rho \theta)$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTHDIV4' :{
    'lo_name'   :'horizontal divergence of potential temperature',
    'label'     :r"$\nabla _{h} (v_{h} \rho \theta)$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVDIV4' :{
    'lo_name'   :'vertical divergence of potential temperature',
    'label'     :r"$\frac{\partial (w \rho \theta)}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},

'POTTHDIVMBLI' :{
    'lo_name'   :'mean horizontal divergence of potential temperature in MBL',
    'label'     :r"$v_{h}\nabla _{h} \theta |_{MBL}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVFLXWPOS' :{
    'lo_name'   :'vertical flux of potential temperature in updrafts',
    'label'     :r"$w_{+} \rho \theta$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'POTTVFLXWPOS' :{
    'lo_name'   :'vertical flux of potential temperature in downdrafts',
    'label'     :r"$w_{-} \rho \theta$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'DIABHMINV' :{
    'lo_name'   :'mean MBL top diabatic heating',
    'label'     :'mean MBL top diabatic heating',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},


'EQPOTTDIV' :{
    'lo_name'   :'divergence of equivalent potential temperature',
    'label'     :r"$v\nabla \theta _e$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'EQPOTTHDIV' :{
    'lo_name'   :'horizontal divergence of equivalent potential temperature',
    'label'     :r"$v_{h}\nabla _{h} \theta _e$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'EQPOTTVDIV' :{
    'lo_name'   :'vertical divergence of equivalent potential temperature',
    'label'     :r"$w\frac{\partial \theta _e}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'EQPOTTDIV3' :{
    'lo_name'   :'divergence of equivalent potential temperature',
    'label'     :r"$\nabla v\theta _e$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'EQPOTTHDIV3' :{
    'lo_name'   :'horizontal divergence of equivalent potential temperature',
    'label'     :r"$\nabla _{h} v_{h}\theta _e$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},
'EQPOTTVDIV3' :{
    'lo_name'   :'vertical divergence of equivalent potential temperature',
    'label'     :r"$\frac{\partial w\theta _e}{\partial z}$",
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :3600*24,
    'plt_units' :'$K$ $d^{-1}$',
},


'TKE' :{
    'lo_name'   :'specific turbulent kinetic energy',
    'label'     :'TKE',
    #'units'     :'$m^{2}$ $s^{-2}$',
    'units'     :'$J$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'TKEV' :{
    'lo_name'   :'specific turbulent kinetic energy in vertical direction',
    'label'     :"w'w'",
    'units'     :'$m^{2}$ $s^{-2}$',
    #'units'     :'$J$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'TKEMBLI' :{
    'lo_name'   :'mean specific turbulent kinetic energy within BL',
    'label'     :'TKE',
    'units'      :'$m^{2}$ $s^{-2}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'FQVZ' :{
    'lo_name'   :'vertical water vapor flux',
    'label'     :'vapor flux',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'WMBLI' :{
    'lo_name'   :'mean w BL',
    'label'     :'mean vertical wind below BL inversion',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'WFLXNORMI' :{
    'lo_name'   :'resolved vertical mass flux',
    'label'     :'vertical mass flux',
    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'AWNORMI' :{
    'lo_name'   :'velocity of vertical circulations',
    'label'     :'|w|',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'AWDNORMI' :{
    'lo_name'   :'downward velocity of vertical circulations',
    'label'     :'w up',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'AWUNORMI' :{
    'lo_name'   :'upward velocity of vertical circulations',
    'label'     :'w down',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'KEWNORMI' :{
    'lo_name'   :'grid-scale vertical kinetic energy',
    'label'     :'grid-scale vertical kinetic energy',
    'units'      :'$J$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'AWMBLI' :{
    'lo_name'   :'mean velocity of vertical circulations',
    'label'     :'|w|$_{MBL}$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'KEWMBLI' :{
    'lo_name'   :'mean vertical resolved kinetic energy below BL inversion',
    'label'     :'grid-scale vertical kinetic energy',
    'units'      :'$J$ $m^{-3}$',
    'dims'      :[dimx,dimy,dimt],
},
'SUBS' :{
    'lo_name'   :'subsidence strength',
    'label'     :'subsidence at 500 hPa',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :3600,
    'plt_units' :'$m$ $h^{-1}$',
},
'SUBSOMEGA' :{
    'lo_name'   :'subsidence strength',
    'label'     :'subsidence at 500 hPa',
    'units'     :'$Pa$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :36,
    'plt_units' :'$hPa$ $h^{-1}$',
},


'ZCPTPP' :{
    'lo_name'   :'altitude of cold-point tropopause',
    'label'     :'$z_T$',
    'units'      :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'PCPTPP' :{
    'lo_name'   :'pressure of cold-point tropopause',
    'label'     :'$p_T$',
    'units'      :'$Pa$',
    'dims'      :[dimx,dimy,dimt],
},
'INVHGT' :{
    'lo_name'   :'height of maximum inversion strength',
    #'label'     :'inversion height',
    'label'     :'$z_i$',
    'units'      :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'LTS' :{
    'lo_name'   :'lower tropospheric stability',
    'label'     :'LTS',
    'units'      :'$K$',
    #'units'      :'$K/100m$',
    'dims'      :[dimx,dimy,dimt],
},
'EIS' :{
    'lo_name'   :'estimated inversion strength',
    'label'     :'EIS',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimt],
},
'LCL' :{
    'lo_name'   :'lifting condensation level',
    'label'     :'LCL',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'LCLNORMI' :{
    'lo_name'   :'lifting condensation level',
    'label'     :'LCL',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'DCLDBASELCL' :{
    'lo_name'   :'difference between cloud base and lifting condensation level',
    'label'     :'cloud base - LCL',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'DINVHGTLCL' :{
    'lo_name'   :'difference between inversion height and lifting condensation level',
    'label'     :'inversion height - LCL',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'DINVHGTLOWCLDBASE' :{
    'lo_name'   :'difference between inversion height and low cloud base',
    'label'     :'dinvcldb',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'PVAP' :{
    'lo_name'   :'vapor pressure',
    'label'     :'$e$',
    'units'     :'$Pa$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'PVAPSATL' :{
    'lo_name'   :'saturation vapor pressure with respect to liquid water',
    'label'     :'$e_{s,l}$',
    'units'     :'$Pa$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'PVAPSATS' :{
    'lo_name'   :'saturation vapor pressure with respect to ice',
    'label'     :'$e_{s,s}$',
    'units'     :'$Pa$',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'QVSAT' :{
    'lo_name'   :'saturation specific humidity',
    'label'     :'$q_v^{s}$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'QVSATDEF' :{
    'lo_name'   :'saturation deficit in terms of specific humidity',
    'label'     :'$q_v^{sd}$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'RH' :{
    'lo_name'   :'relative humidity',
    'label'     :'RH',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :100,
    'plt_units' :'%',
},
'dRHdt' :{
    'lo_name'   :'relative humidity tendency',
    'label'     :'RH',
    'units'     :'$s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :100*3600,
    'plt_units' :'% $h^{-1}$',
},
'dRHdt_MBL_FLX' :{
    'lo_name'   :'MBL relative humidity tendency due to surface fluxes',
    'label'     :'RH',
    'units'     :'$s^{-1}$',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :100*3600,
    'plt_units' :'% $h^{-1}$',
},
#'RHL' :{
#    'lo_name'   :'relative humidity with respect to liquid water',
#    'label'     :'$RH_{l}$',
#    'units'     :'',
#    'dims'      :[dimx,dimy,dimz,dimt],
#},
'RHLNORMI' :{
    'lo_name'   :'relative humidity',
    'label'     :'RH',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
},
#'RHLNORMI' :{
#    'lo_name'   :'relative humidity with respect to liquid water',
#    'label'     :'$RH_{l}$',
#    'units'     :'',
#    'dims'      :[dimx,dimy,dimz,dimt],
#},
'INVF' :{
    'lo_name'   :'frequency of inversion',
    'label'     :'occurrence of inversion',
    'units'     :'',
    'dims'      :[dimx,dimy,dimt],
},
'INVSTRA' :{
    'lo_name'   :'average inversion strength',
    'label'     :'inversion strength',
    'units'     :'$K$ $m^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'INVSTR' :{
    'lo_name'   :'inversion strength',
    'label'     :'inversion strength',
    'units'     :'$K$',
    'dims'      :[dimx,dimy,dimt],
},
'INVSTRV' :{
    'lo_name'   :'inversion strength using virtual potential temperature',
    'label'     :'INV',
    'units'     :'$K$',
    'dims'      :[dimx,dimy,dimt],
},
'CLDHGT' :{
    'lo_name'   :'height of maximum cloud water content',
    'label'     :'cloud height',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
#'CLDMASK@DARDAR_CLOUD' :{
#    'lo_name'   :'cloud mask on DARDAR_CLOUD tracks',
#    'label'     :'cloud mask',
#    'units'     :'',
#    'dims'      :[dimz,dimt],
#},
'CLDF' :{
    'lo_name'   :'total cloud fraction',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'%',
},
'LCLDF1E-3' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 1e-3 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF5E-4' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 5e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF2E-4' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 2e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF1E-4' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 1e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF5E-5' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 5e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF2E-5' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 2e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF1E-5' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 1e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF1E-3' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 1e-3 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF5E-4' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 5e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF2E-4' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 2e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF1E-4' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 1e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF5E-5' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 5e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF2E-5' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 2e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF1E-5' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 1e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF1E-3NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 1e-3 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF5E-4NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 5e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF2E-4NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 2e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF1E-4NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 1e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF5E-5NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 5e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF2E-5NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 2e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LCLDF1E-5NORMI' :{
    'lo_name'   :'liquid cloud fraction derived with threhshold 1e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF1E-3NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 1e-3 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF5E-4NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 5e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF2E-4NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 2e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF1E-4NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 1e-4 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF5E-5NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 5e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF2E-5NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 2e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'ICLDF1E-5NORMI' :{
    'lo_name'   :'ice cloud fraction derived with threhshold 1e-5 kg kg-1',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'CLDMASK' :{
    'lo_name'   :'cloud mask',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'CLDMASKNORMI' :{
    'lo_name'   :'cloud mask',
    'label'     :'cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
    'plt_fact'  :1E2,
    'plt_units' :'',
},
'LOWCLDF' :{
    'lo_name'   :'low-cloud fraction',
    'label'     :'low-cloud fraction',
    'units'     :'',
    'dims'      :[dimx,dimy,dimz,dimt],
},
'LOWCLDBASE' :{
    'lo_name'   :'height of low cloud base',
    'label'     :'cloud base height',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},
'LOWCLDBASENORMI' :{
    'lo_name'   :'height of low cloud base normalised by inversion height',
    'label'     :'relative cloud base height',
    'units'     :'',
    'dims'      :[dimx,dimy,dimt],
},
'LCLDDEPTH' :{
    'lo_name'   :'thickness of low cloud top',
    'label'     :'cloud depth',
    'units'     :'$m$',
    'dims'      :[dimx,dimy,dimt],
},





'SWUTOA' :{
    'lo_name'   :'upward SW radiative flux at TOA',
    'label'     :'$SW^{\u2191}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CSWUTOA' :{
    'lo_name'   :'clear-sky reflected SW radiative flux at TOA',
    'label'     :'$SW^{cs,\u2191}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWUSFC' :{
    'lo_name'   :'upward SW radiative flux at surface',
    'label'     :'$SW^{\u2191}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWDIFUSFC' :{
    'lo_name'   :'upward diffuse SW radiative flux at surface',
    'label'     :'$SW^{\u2191}_{dif,SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWDTOA' :{
    'lo_name'   :'downward SW radiative flux at TOA',
    'label'     :'$SW^{\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWDSFC' :{
    'lo_name'   :'downward SW radiative flux at surface',
    'label'     :'$SW^{\u2193}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWDIRDSFC' :{
    'lo_name'   :'downward direct SW radiative flux at surface',
    'label'     :'$SW^{\u2190}_{dir,SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWDIFDSFC' :{
    'lo_name'   :'downward diffuse SW radiative flux at surface',
    'label'     :'$SW^{\u2190}_{dif,SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWNDTOA' :{
    'lo_name'   :'net downward SW radiative flux at TOA',
    #'label'     :'$SW^{\u2193-\u2191}_{TOA}$',
    'label'     :'$SW^{net\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWNUSFC' :{
    'lo_name'   :'net upward SW radiative flux at surface',
    'label'     :'$SW^{\u2191-\u2193}_{SFC}$',
    'glabel'    :'upward flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CSWNDTOA' :{
    'lo_name'   :'clear-sky net downward SW radiative flux at TOA',
    #'label'     :'$SW^{cs,\u2193-\u2191}_{TOA}$',
    'label'     :'$SW^{cs,net\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRESWNDTOA' :{
    'lo_name'   :'cloud radiative effect on net downward SW radiative flux at TOA',
    #'label'     :'$CRE^{SW^{\u2193-\u2191}}_{TOA}$',
    #'label'     :'$CRE^{SW^{net\u2193}}_{TOA}$',
    'label'     :'SW CRE',
    #'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SWNDSFC' :{
    'lo_name'   :'net downward SW radiative flux at surface',
    'label'     :'$SW^{\u2193-\u2191}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CSWNDSFC' :{
    'lo_name'   :'clear-sky net downward SW radiative flux at surface',
    'label'     :'$SW^{cs,\u2193-\u2191}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRESWNDSFC' :{
    'lo_name'   :'cloud radiative effect on net downward SW radiative flux at surface',
    'label'     :'$CRE^{SW^{\u2193-\u2191}}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},





'LWUTOA' :{
    'lo_name'   :'outgoing LW radiative flux at TOA',
    #'label'     :'$LW^{\u2191}_{TOA}$',
    'label'     :'OLR',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CLWUTOA' :{
    'lo_name'   :'clear-sky outgoing LW radiative flux at TOA',
    'label'     :'$LW^{cs,\u2191}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRELWUTOA' :{
    'lo_name'   :'cloud radiative effect on outgoing LW radiative flux at TOA',
    'label'     :'$CRE^{LW^{\u2191}}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'LWUSFC' :{
    'lo_name'   :'upward LW radiative flux at surface',
    'label'     :'$LW^{\u2191}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'LWDTOA' :{
    'lo_name'   :'downward LW radiative flux at TOA',
    #'label'     :'$LW^{\u2193}_{TOA}$',
    'label'     :'$LW^{net\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CLWDTOA' :{
    'lo_name'   :'clear-sky downward LW radiative flux at TOA',
    #'label'     :'$LW^{cs,\u2193}_{TOA}$',
    'label'     :'$LW^{cs,net\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRELWDTOA' :{
    'lo_name'   :'cloud radiative effect on downward LW radiative flux at TOA',
    #'label'     :'$CRE^{LW^{\u2193}}_{TOA}$',
    'label'     :'$CRE^{LW^{net\u2193}}_{TOA}$',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'LWDSFC' :{
    'lo_name'   :'downward LW radiative flux at surface',
    'label'     :'$LW^{\u2193}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CLWDSFC' :{
    'lo_name'   :'clear-sky downward LW radiative flux at surface',
    'label'     :'$LW^{\u2193}_{cs,SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'LWNUSFC' :{
    'lo_name'   :'net upward LW radiative flux at surface',
    'label'     :'$LW^{\u2191-\u2193}_{SFC}$',
    'glabel'    :'upward flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'LWNDSFC' :{
    'lo_name'   :'net downward LW radiative flux at surface',
    'label'     :'$LW^{\u2193-\u2191}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CLWNDSFC' :{
    'lo_name'   :'clear-sky net downward LW radiative flux at surface',
    'label'     :'$LW^{cs,\u2193-\u2191}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRELWNDSFC' :{
    'lo_name'   :'cloud radiative effect on net downward LW radiative flux at surface',
    'label'     :'$CRE^{LW^{\u2193-\u2191}}_{SFC}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'LWDIVATM' :{
    'lo_name'   :'net LW flux out of the atmosphere',
    'label'     :'$LW^{\u2191}_{TOA}+LW^{net\u2193}_{SFC}$',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CLWDIVATM' :{
    'lo_name'   :'net clear-sky LW flux out of the atmosphere',
    'label'     :'$LW^{cs,\u2191}_{TOA}+LW^{cs,net\u2193}_{SFC}$',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRELWDIVATM' :{
    'lo_name'   :'net CRE LW flux out of the atmosphere',
    'label'     :'$LW^{CRE,\u2191}_{TOA}+LW^{CRE,net\u2193}_{SFC}$',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},


'ALBEDO' :{
    'lo_name'   :'albedo SW',
    'label'     :'albedo',
    'units'     :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'%',
},
'RADNDTOA' :{
    'lo_name'   :'net downward total radiative flux at TOA',
    #'label'     :'net $^{\u2193-\u2191}_{TOA}$',
    'label'     :'TOT$^{net\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRADNDTOA' :{
    'lo_name'   :'clear-sky net downward total radiative flux at TOA',
    #'label'     :'clear-sky net $^{\u2193-\u2191}_{TOA}$',
    'label'     :'TOT$^{cs,net\u2193}_{TOA}$',
    'glabel'    :'flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'CRERADNDTOA' :{
    'lo_name'   :'cloud radiative effect on net downward total radiative flux at TOA',
    #'label'     :'$CRE^{rad^{\u2193-\u2191}}_{TOA}$',
    'label'     :'$CRE^{TOT^{net\u2193}}_{TOA}$',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},


'U10M' :{
    'lo_name'   :'U wind at 10m',
    'label'     :'u wind',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'U10M_W' :{
    'lo_name'   :'U wind at 10m at western domain boundary',
    'label'     :'u wind',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimy,dimt],
},
'U10M_E' :{
    'lo_name'   :'U wind at 10m at eastern domain boundary',
    'label'     :'u wind',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimy,dimt],
},
'V10M_S' :{
    'lo_name'   :'V wind at 10m at southern domain boundary',
    'label'     :'v wind',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimt],
},
'V10M_N' :{
    'lo_name'   :'V wind at 10m at northern domain boundary',
    'label'     :'v wind',
    'units'     :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimt],
},
'V10M' :{
    'lo_name'   :'V wind at 10m',
    'label'     :'v wind',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'PS' :{
    'lo_name'   :'surface pressure',
    'label'     :'pressure',
    'units'      :'$hPa$',
    'dims'      :[dimx,dimy,dimt],
},
'UV10M' :{
    'lo_name'   :'wind speed at 10m',
    #'label'     :'10m-wind',
    'label'     :'V$_{10m}$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'SLHFLX' :{
    'lo_name'   :'surface latent heat flux',
    'label'     :'LH',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :24*3600*1000/(CON_LH_EVAP*1000), # SLHFLX/(CON_LH_EVAP*density_water)*24h/d*3600s/h*1000mm/m
    #'plt_units' :'$mm$ $d^{-1}$',
},
'dQVdt_MBL_LH' :{
    'lo_name'   :'moistening rate of the MBL due to surface latent heat flux',
    'label'     :'dQV dt',
    'units'     :'$kg$ $kg^{-1}$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :3600*1000,
    'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
},
'dTdt_MBL_SH' :{
    'lo_name'   :'heating rate of the MBL due to surface sensible heat flux',
    'label'     :'dT dt',
    'units'     :'$K$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :3600,
    'plt_units' :'$K$ $h^{-1}$',
},
'SSHFLX' :{
    'lo_name'   :'surface sensible heat flux',
    #'label'     :'sensible heat flux',
    'label'     :'SHF',
    'glabel'    :'upward flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'SBUOYIFLX' :{
    'lo_name'   :'surface buoyancy flux',
    'label'     :'B',
    'units'      :'$m^2$ $s^{-3}$',
    'dims'      :[dimx,dimy,dimt],
},
'ENFLXNUSFC' :{
    'lo_name'   :'net upward energy flux at surface',
    'label'     :'net $^{\u2191-\u2193}_{SFC}$',
    'glabel'    :'upward flux',
    'units'     :'$W$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},

'TQC' :{
    'lo_name'   :'liquid water path',
    'label'     :'LWP',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3,
    'plt_units' :'$g$ $m^{-2}$',
},
'CORREFL' :{
    #'lo_name'   :'corrected reflectance',
    #'label'     :'reflectance',
    'lo_name'   :'liquid water path',
    'label'     :'liquid water path',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'TQI' :{
    'lo_name'   :'ice water path',
    'label'     :'ice water path',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3,
    'plt_units' :'$g$ $m^{-2}$',
},
'TQR' :{
    'lo_name'   :'rain water path',
    'label'     :'rain water path',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3,
    'plt_units' :'$g$ $m^{-2}$',
},
'TQG' :{
    'lo_name'   :'graupel water path',
    'label'     :'graupel water path',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3,
    'plt_units' :'$g$ $m^{-2}$',
},
'TQS' :{
    'lo_name'   :'snow water path',
    'label'     :'snow water path',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1E3,
    'plt_units' :'$g$ $m^{-2}$',
},
'TQV' :{
    'lo_name'   :'water vapor path',
    'label'     :'water vapor path',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
'DQVINV' :{
    'lo_name'   :'specific humidity jump across the inversion',
    'label'     :'$\Delta q_v ^{inv}$',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'ENTRDRY' :{
    'lo_name'   :'bulk entrainment drying',
    'label'     :'entr. drying',
    #'units'      :'$kg$ $kg^{-1}$ $s^{-1}$',
    'units'      :'$m$ $s^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    #'plt_fact'  :1000*3600,
    #'plt_units' :'$g$ $kg^{-1}$ $h^{-1}$',
    'plt_fact'  :-1000*3600*24,
    'plt_units' :'$mm$ $d^{-1}$',
},
'TQVFT' :{
    'lo_name'   :'water vapor path between 3km an 6km',
    'label'     :'water vapor path (3-6km)',
    'units'      :'$kg$ $m^{-2}$',
    'dims'      :[dimx,dimy,dimt],
},
#'QVFLXZCB' :{
#    'lo_name'   :'qv-flux at cloud base',
#    'label'     :'',
#    'units'      :'$kg$ $m^{-2}$ $s^{-1}$',
#    'dims'      :[dimx,dimy,dimt],
#},
'CAPE' :{
    'lo_name'   :'convective available potential energy',
    'label'     :'CAPE',
    'units'     :'$J$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'CIN' :{
    'lo_name'   :'convectivion inhibition',
    'label'     :'CIN',
    'units'     :'$J$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},

'CLCL' :{
    'lo_name'   :'low cloud cover',
    'label'     :'low cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'%',
},
'CLCL2' :{
    'lo_name'   :'low cloud cover',
    'label'     :'low cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'%',
},
'CLCM' :{
    'lo_name'   :'mid cloud cover',
    'label'     :'mid cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'%',
},
'CLCH' :{
    'lo_name'   :'high cloud cover',
    'label'     :'high cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'%',
},
'CLCT' :{
    'lo_name'   :'total cloud over',
    'label'     :'cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'',
},
'CLCW' :{
    'lo_name'   :'water cloud cover',
    'label'     :'water cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'',
},
'CLCI' :{
    'lo_name'   :'ice cloud cover',
    'label'     :'ice cloud cover',
    'units'      :'',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :100,
    'plt_units' :'',
},
'PP' :{
    'lo_name'   :'precipitation',
    'label'     :'precip.',
    'units'      :'$mm$ $h^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :24,
    'plt_units' :'$mm$ $d^{-1}$',
},
'PPGRID' :{
    'lo_name'   :'grid-scale precipitation',
    'label'     :'precipitation',
    'units'      :'$mm$ $h^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
'PPCONV' :{
    'lo_name'   :'convective precipitation',
    'label'     :'precipitation',
    'units'      :'$mm$ $h^{-1}$',
    'dims'      :[dimx,dimy,dimt],
},
#'PPANVI' :{
#    'lo_name'   :'anvil precipitation',
#    'label'     :'precipitation',
#    'units'      :'$mm$ $h^{-1}$',
#    'dims'      :[dimx,dimy,dimt],
#},
'QV2M' :{
    'lo_name'   :'2m specific humidity',
    'label'     :'surface qv',
    'units'      :'$kg$ $kg^{-1}$',
    'dims'      :[dimx,dimy,dimt],
    'plt_fact'  :1000,
    'plt_units' :'$g$ $kg^{-1}$',
},
'T2M' :{
    'lo_name'   :'2m temperature',
    'label'     :'T$_{2m}$',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimt],
},
'TSURF' :{
    'lo_name'   :'surface temperature',
    'label'     :'T$_{sfc}$',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimt],
},
'SST' :{
    'lo_name'   :'sea surface temperature',
    'label'     :'SST',
    'units'      :'$K$',
    'dims'      :[dimx,dimy,dimt],
},

'PARCBUOYI' :{
    'lo_name'   :'parcel buoyancy',
    'label'     :'parcel buoyancy',
    'units'      :'$m$ $s^{-2}$',
    'dims'      :[dimz],
},
'PARCTV' :{
    'lo_name'   :'parcel virtual temperature',
    'label'     :'parcel virtual temperature',
    'units'      :'$K$',
    'dims'      :[dimz],
},
'PARCT' :{
    'lo_name'   :'parcel temperature',
    'label'     :'parcel temperature',
    'units'      :'$K$',
    'dims'      :[dimz],
},



'bulk_tend_edge_POTT_below_S' :{
    'lo_name'   :'bulk domain MBL temperature tendency due to advection from South',
    'label'     :'South flux pot. temp. tendency',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimt],
},
'bulk_tend_edge_POTT_below_E' :{
    'lo_name'   :'bulk domain MBL temperature tendency due to advection from East',
    'label'     :'East flux pot. temp. tendency',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimt],
},
'bulk_tend_edge_POTT_below_N' :{
    'lo_name'   :'bulk domain MBL temperature tendency due to advection from North',
    'label'     :'North flux pot. temp. tendency',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimt],
},
'bulk_tend_edge_POTT_below_W' :{
    'lo_name'   :'bulk domain MBL temperature tendency due to advection from West',
    'label'     :'West flux pot. temp. tendency',
    'units'      :'$K$ $s^{-1}$',
    'dims'      :[dimt],
},







# Master thesis stuff
'WVP_0_10' : {
    'label'         :'Water Vapor Path',
    'units'          :'[kg m-2]',
},
'WVP_0_4' : {
    'label'         :'Water Vapor Path',
    'units'          :'[kg m-2]',
},
'WVP_0_2' : {
    'label'         :'Water Vapor Path',
    'units'          :'[kg m-2]',
},
'WVP_2_4' : {
    'label'         :'Water Vapor Path',
    'units'          :'[kg m-2]',
},
'WVP_2_10' : {
    'label'         :'Water Vapor Path',
    'units'          :'[kg m-2]',
},
'WVP_4_10' : {
    'label'         :'Water Vapor Path',
    'units'          :'[kg m-2]',
},
}


### clear-sky and in-cloud and updraft
for var_name in [
    'POTTHDIV','POTTVDIV','POTTDIV',
    'POTTHDIV3','POTTVDIV3','POTTDIV3',
    'POTTHDIVTURB','POTTVDIVTURB','POTTDIVTURB',
    'POTTHDIVMEAN','POTTVDIVMEAN','POTTDIVMEAN',
    'EQPOTTDIV','LATH',
    'EQPOTTDIV3',
    'QVHDIV','QVVDIV','QVDIV',
    'QVHDIV2','QVVDIV2','QVDIV2',
    'QVHDIV3','QVVDIV3','QVDIV3',
    'QVHDIVTURB','QVVDIVTURB','QVUVDIVTURB','QVDVDIVTURB','QVDIVTURB',
    'QVHDIV2TURB','QVVDIV2TURB','QVDIV2TURB',
    'QVHDIV3TURB','QVVDIV3TURB','QVDIV3TURB',
    'QCHDIV','QCVDIV','QCDIV',
    'QCHDIVTURB','QCVDIVTURB','QCDIVTURB',
    'QVSATDEF','QV','W','RH','TKEV',
    'WFLX','BVF','T','TV','TDEW',
    'UVDIV',
    ]:

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'in-cloud ' + entry['lo_name']
    entry['label'] = 'in-cloud ' + entry['label']
    nlv['CLD{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'clear-sky ' + entry['lo_name']
    entry['label'] = 'clear-sky ' + entry['label']
    nlv['CS{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = entry['lo_name']+'$|_{IWP=0}$'
    entry['label'] = entry['label']+'$|_{IWP=0}$'
    nlv['NCOLI{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'updraft ' + entry['lo_name']
    entry['label'] = 'updraft ' + entry['label']
    nlv['UPD{}'.format(var_name)] = entry


### relative humidity binning
for var_name in [
    'CSPOTTDIV3',
    ]:
    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'low-RH ' + entry['lo_name']
    entry['label'] = 'low-RH ' + entry['label']
    nlv['RH0L{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'mid-RH ' + entry['lo_name']
    entry['label'] = 'mid-RH ' + entry['label']
    nlv['RH1L{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'high-RH ' + entry['lo_name']
    entry['label'] = 'high-RH ' + entry['label']
    nlv['RH2L{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'low-RH ' + entry['lo_name']
    entry['label'] = 'low-RH ' + entry['label']
    nlv['RH0G{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'mid-RH ' + entry['lo_name']
    entry['label'] = 'mid-RH ' + entry['label']
    nlv['RH1G{}'.format(var_name)] = entry

    entry = copy.copy(nlv[var_name])
    entry['lo_name'] = 'high-RH ' + entry['lo_name']
    entry['label'] = 'high-RH ' + entry['label']
    nlv['RH2G{}'.format(var_name)] = entry


### NORMI (alt normalized by local inversion alt)
for var_name in [
    'BUOYIFLX','TKE','QC','T','POTT','POTTV','CLDF',
    'QV','CSQV','CLDQV',
    'W','CSW','CLDW',
    'RH','CSRH','CLDRH',
    'TKEV','CSTKEV','CLDTKEV',
    'QVSATDEF',
    'POTTHDIV','POTTVDIV','POTTDIV',
    'CLDPOTTHDIV','CLDPOTTVDIV','CLDPOTTDIV',
    'CSPOTTHDIV','CSPOTTVDIV','CSPOTTDIV',
    'POTTHDIV3','POTTVDIV3','POTTDIV3',
    'CLDPOTTHDIV3','CLDPOTTVDIV3','CLDPOTTDIV3',
    'CSPOTTHDIV3','CSPOTTVDIV3','CSPOTTDIV3',
    'POTTHDIVTURB','POTTVDIVTURB','POTTDIVTURB',
    'CLDPOTTHDIVTURB','CLDPOTTVDIVTURB','CLDPOTTDIVTURB',
    'CSPOTTHDIVTURB','CSPOTTVDIVTURB','CSPOTTDIVTURB',
    'POTTHDIVMEAN','POTTVDIVMEAN','POTTDIVMEAN',
    'EQPOTTDIV','LATH',
    'EQPOTTDIV3',
    'CLDEQPOTTDIV','CLDLATH',
    'CSEQPOTTDIV','CSLATH',
    'QVHDIV','QVVDIV','QVDIV',
    'QVHDIV2','QVVDIV2','QVDIV2',
    'QVHDIV3','QVVDIV3','QVDIV3',
    'CLDQVHDIV','CLDQVVDIV','CLDQVDIV',
    'CLDQVHDIV2','CLDQVVDIV2','CLDQVDIV2',
    'CLDQVHDIV3','CLDQVVDIV3','CLDQVDIV3',
    'CSQVHDIV','CSQVVDIV','CSQVDIV',
    'CSQVHDIV2','CSQVVDIV2','CSQVDIV2',
    'CSQVHDIV3','CSQVVDIV3','CSQVDIV3',
    'QVHDIVTURB','QVVDIVTURB','QVUVDIVTURB','QVDVDIVTURB','QVDIVTURB',
    'QVHDIV2TURB','QVVDIV2TURB','QVDIV2TURB',
    'QVHDIV3TURB','QVVDIV3TURB','QVDIV3TURB',
    'CLDQVHDIVTURB','CLDQVVDIVTURB','CLDQVUVDIVTURB','CLDQVDVDIVTURB','CLDQVDIVTURB',
    'CLDQVHDIV2TURB','CLDQVVDIV2TURB','CLDQVDIV2TURB',
    'CLDQVHDIV3TURB','CLDQVVDIV3TURB','CLDQVDIV3TURB',
    'CSQVHDIVTURB','CSQVVDIVTURB','CSQVUVDIVTURB','CSQVDVDIVTURB','CSQVDIVTURB',
    'CSQVHDIV2TURB','CSQVVDIV2TURB','CSQVDIV2TURB',
    'CSQVHDIV3TURB','CSQVVDIV3TURB','CSQVDIV3TURB',
    'QVHDIVMEAN','QVVDIVMEAN','QVDIVMEAN',
    'QVHDIV2MEAN','QVVDIV2MEAN','QVDIV2MEAN',
    'QVHDIV3MEAN','QVVDIV3MEAN','QVDIV3MEAN',
    'QCHDIV','QCVDIV','QCDIV',
    'CLDQCHDIV','CLDQCVDIV','CLDQCDIV',
    'CSQCHDIV','CSQCVDIV','CSQCDIV',
    'QCHDIVTURB','QCVDIVTURB','QCDIVTURB',
    'CLDQCHDIVTURB','CLDQCVDIVTURB','CLDQCDIVTURB',
    'CSQCHDIVTURB','CSQCVDIVTURB','CSQCDIVTURB',
    'QCHDIVMEAN','QCVDIVMEAN','QCDIVMEAN',
    'CSQVSATDEF','CLDQVSATDEF',
    ]:
    nlv['{}NORMI'.format(var_name)] = copy.copy(nlv[var_name])



def add_var_attributes(var, var_name):
    var.attrs['units'] = nlv[var_name]['units']
    var.attrs['standard_name'] = nlv[var_name]['label']
    var.attrs['long_name'] = nlv[var_name]['lo_name']
    var.name = var_name
    return(var)

def get_plt_fact(var_name):
    if 'plt_fact' in nlv[var_name]:
        return(nlv[var_name]['plt_fact'])
    else:
        return(1)

def get_plt_units(var_name):
    if 'plt_units' in nlv[var_name]:
        return(nlv[var_name]['plt_units'])
    else:
        return(nlv[var_name]['units'])
